### PR TITLE
Update version to 2.7.3 in Makefile and app file

### PR DESCRIPTION
**Pull request by stoshfabricius**
Update the Makefile and app file to the new version number to match the version requirements in the new release of [cowboy](https://github.com/ninenines/cowboy/commit/d5489b4c7360ebcb134db892fac50a2d7d406402)

### CODE REVIEW

**Comment by chulkilee** [comment]
Probably need to yank 2.7.2 and release 2.7.3 ? I don't think it's possible to *update* existing hex package - since mix.lock has checksum.

**Comment by chulkilee** [comment]
But I'm surprised it's not caught when uploading to hex. How can a hex package can be uploaded in different version? Probably hex server/client bug? I thought when uploading to hex, it checks the version from code..

**Comment by stoshfabricius** [comment]
@chulkilee yes that is a good point, I will update to `2.7.3` assuming that this would be a new release.

Also `cowboy` may need to be updated to reference this new release number since it looks like from the last commit on cowboy it's referencing 2.7.2 directly

**Comment by essen** [comment]
Merged, thanks! Also added a target to help me release in the future without making mistakes like this.

**Pull request closed without merging**
