### PR TITLE
Fix badarg in http/2 ping generation.

### PR DESCRIPTION
**Pull request by philipstears**

### CODE REVIEW

**Comment by essen** [comment]
Don't think that's the right approach, because of https://github.com/philipstears/cowlib/blob/4d005a694b1582a358e0904ed9345c3fa0d122f0/src/cow_http2.erl#L192

What's the exact issue? Does gun do something incorrect there?

**Comment by philipstears** [comment]
Gun is currently passing through 64 zeroed bits:

https://github.com/ninenines/gun/blob/master/src/gun_http2.erl#L200

Should it just pass numeric zero instead?

**Comment by essen** [comment]
Yep. At least for now. Dunno if integer is a good representation but can always change it later.

**Comment by philipstears** [comment]
Sure thing; makes sense.

**Pull request closed without merging**
