### PR TITLE
Accept setting samesite to none

### PR DESCRIPTION
**Pull request by aholmn**

### CODE REVIEW

**Comment by essen** [comment]
Why?

Also even if the value `none` was allowed, nothing should be sent, because sending nothing is the same as sending "None" or any other value that's different from "Strict" or "Lax". See https://httpwg.org/http-extensions/draft-ietf-httpbis-rfc6265bis.html#the-samesite-attribute

**Comment by aholmn** [comment]
In latest chrome the new default is LAX when its left out.

**Comment by essen** [comment]
OK for future reference https://www.chromestatus.com/feature/5088147346030592 has the details.

**Comment by aholmn** [comment]
Does it make sense merging this, because else you wont be able to get Samesite=None in later versions of chrome, which will make it impossible to send cookies from an iframe to another domain.

**Comment by essen** [comment]
Yes the PR is fine, not counting the whitespace. I'm currently busy with Gun so I'll merge when I get back to Cowboy/Cowlib matters.

**Comment by essen** [comment]
Merged, thanks!

**Pull request closed without merging**
