### PR TITLE
Http2 fixes

### PR DESCRIPTION
**Pull request by ppolv**

### CODE REVIEW

**Comment by essen** [comment]
Thanks!

**Comment by essen** [comment]
I'll do the merge tomorrow.

In the future, please don't use eunit macros (or include the header at all). I really meant what I said, I wanted X = function(A), X = function(B), X = function(C) ..., not some hard to decipher mix of lists comprehensions, macro that creates funs and returns them to eventually make eunit run them. Simple is good.

I'll do the change when merging though so don't worry about it for now.

**Comment by essen** [comment]
It looks like I underestimated how many bytes are in ping frames, so I kept the list comprehension, but otherwise did the changes as noted. I also added a case to check the remainder of the binary after parsing.

As for the HPACK tests, the values are not magic, they come from the Appendix C of the RFC, so I put them back as they should have been in the first place. Original error was probably due to thinking too much instead of copy pasting. Those tests reproduce exactly the appendix examples.

Merged, thanks!

**Comment by ppolv** [comment]
Thanks a lot!

**Pull request closed without merging**
