### PR TITLE
Websocket compression

### PR DESCRIPTION
**Pull request by vans163**
Related to https://github.com/ninenines/cowboy/pull/945

### CODE REVIEW

**Comment by essen** [comment]
Why did you remove validate_permessage_deflate?

**Comment by vans163** [comment]
It was not being called by anything from static analysis.

**Comment by essen** [comment]
It's called by at least the Gun client. This is a library for many projects...

**Comment by vans163** [comment]
Ah I was not aware, it should be refactored then, I mean the same exact code was in two different places.

**Comment by essen** [comment]
If Cowboy has the same code then Cowboy should call it.

**Comment by essen** [comment]
I've pushed configuration of Websocket deflate options. I will do the compression bit later. Closing since there's a ticket for it at https://github.com/ninenines/cowboy/issues/1105 Thanks!

**Pull request closed without merging**
