### PR TITLE
Fix compilation via Elixir/Mix

### PR DESCRIPTION
**Pull request by tolbrino**
I might have overlooked the reason for not using a `.app.src` file, so feel free to correct me.

### CODE REVIEW

**Comment by ericmj** [comment]
What compilation error are you having with mix?

**Comment by tolbrino** [comment]
No error, it just silently doesn't compile the `.erl` files.

**Comment by ericmj** [comment]
And this change fixes it? Is mix calling `make` or `rebar` to compile this?

**Comment by tolbrino** [comment]
It is calling `make`. I tested it with an updated `erlang.mk` version and that actually works and compiles the `.erl` files. So this doesn't seem to be a Mix issue.

**Comment by ericmj** [comment]
Mix should use the `erlang.mk` in the repository so it could be the case that cowlib's bundled `erlang.mk` is outdated?

**Comment by tolbrino** [comment]
Correct, after a `make erlang-mk` the build works as expected.

**Comment by essen** [comment]
What's the error you got?

**Comment by essen** [comment]
Updated Erlang.mk, but still interested in the error you had.

Closing, thanks!

**Comment by tolbrino** [comment]
The problem was that `make` would not compile the `.erl` files. But since the `.app` file stated that the app contains these modules, I would get `undef` errors at runtime for any call to `cowlib` modules, since the respective `.beam` files where not there.

**Comment by essen** [comment]
Alright. Glad the update just fixed it then. :-) Thanks!

**Pull request closed without merging**
