### PR TITLE
force extension of filename into lower char

### PR DESCRIPTION
**Pull request by DavidAlphaFox**
Dear author.
I use `cow_mimetypes` to detect mimetypes, but sometime the extension of filename in upper char on filesystem.
So I modify `cow_mimetypes`, force extension of filename into lower char.

### CODE REVIEW

**Comment by essen** [comment]
Agree. Maybe use `string:lowercase/1` instead though.

**Comment by DavidAlphaFox** [comment]
Agree, I fixed this.
If the version of OTP is 20 or greater, it will use `string:lowercase`. Otherwise it will use through.

**Comment by DavidAlphaFox** [comment]
OK, I revert the commit. Only support OTP 20 or greater.

**Comment by essen** [comment]
I've merged this locally and this will be part of the next patch release. I've also added a test in Cowboy for cowboy_static relating to this. Thanks!

**Pull request closed without merging**
