### PR TITLE
Add support for SameSite cookies

### PR DESCRIPTION
**Pull request by ECrownofFire**
The SameSite cookie attribute has yet to appear in an official RFC, and
until recently was exclusive to Chrome. However, Firefox has recently
implemented it as well, so it seems prudent to support it.

See https://blog.mozilla.org/security/2018/04/24/same-site-cookies-in-firefox-60/
and https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-02.

### CODE REVIEW

**Comment by essen** [comment]
Is it? The draft has expired. I'll have to double check the status on that.

**Comment by ECrownofFire** [comment]
The draft expired but it seems like Mozilla has gone ahead and implemented it anyway. I'm guessing we'll see a new (final) version of the draft soon-ish.

**Comment by essen** [comment]
Please also do a "make erlang-mk" and commit the erlang.mk in a separate commit.

**Comment by essen** [comment]
OK my bad the necessary Erlang.mk fix was not pushed yet. Don't worry about the test failures, if `make dialyze` works then it's OK.

**Comment by ECrownofFire** [comment]
Yeah `make dialyze` is clean, at least on my system.

(though there's a weird thing where I have to pass in `DIALYZER_OPTS=-nn` and `DIALYZER_PLT_OPTS=-nn` or dialyzer crashes when trying to native-compile some things, but *shrug*, I think it's a Fedora bug or something, idk)

**Comment by essen** [comment]
Maybe you're missing HiPE, or HiPE is broken somehow. An alternative is something like `make dialyze ERLANG_OTP=OTP-20.3.8` which will use kerl to build that version and use it to run the commands, but that's perhaps a bit heavy for something so simple.

**Comment by kjw1** [comment]
Any chance this will be merged soon? I fell down a web security rabbit hole and it sounds like this option is key to preventing some CSRF attacks, and it would be nice to have. If there's some work that needs to be done on it, I could give it a shot, let me know.

**Comment by essen** [comment]
It looks fine as far as I can tell.

The most recent draft is at https://httpwg.org/http-extensions/draft-ietf-httpbis-rfc6265bis.html#the-samesite-attribute and the implementation seems to match that.

How urgent is this for you? I have Cowboy 2.5 basically ready but perhaps I can delay more to include this. If you're fine with overriding the Cowlib dependency I can do both releases independently from each other though.

**Comment by essen** [comment]
I have merged it, if you need me to issue a release, or if you need Cowboy 2.5 to include this, please say. Note that you can always override dependencies even if 2.5 doesn't include it. Thanks!

**Comment by kjw1** [comment]
I updated my dependency to the latest commit and the flag works. Thank you!

**Pull request closed without merging**
