### PR TITLE
Fix http2 settings parsing when there's more data

### PR DESCRIPTION
**Pull request by tony612**
Sometimes, there's more data to come for the SETTINGS frame. There'll be an error when parsing http2 SETTINGS frames, like current data is `<<0,0,0,4,1,0>>`.

### CODE REVIEW

**Comment by essen** [comment]
Makes sense. Please add a test though.

**Comment by tony612** [comment]
@essen Done.

**Comment by tony612** [comment]
@essen ping

**Comment by essen** [comment]
Please don't ping, I've not had a day to work on open source since you submitted the PR.

**Comment by essen** [comment]
Merged, thanks!

**Pull request closed without merging**
